dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
notifications:
  slack:
    rooms:
      secure: ZCN6vUkkOAx1pjhUUquWTKGhVIl6ldDd0NwjWlxGveykATjQuecq4gcax8Rzfrl3IMqJXNH3hrC43XpOJD2+KteU5zAur9VfC9CQgmSyYRKjbZ4O7FZV6DHUCge1J8SzOBjv6RaPw4kMhCdlBYMEHdLgpBSRG1PjNgdJ+QCAQArkV+lDHmMHQ+HKdDiCPQbUZVI6HoRfcZ68F7OA6zijY32weJP81QhUIHNVY51EGunSoMzqCOyzq83lBjQ5LjF60rjVfl5mVSKaV7TzlZ6DII87XfxNMZBQpkUxbVqoJEnvUIu9WVq9g1Y3wpcB4oElDS8zGsCO7cPUyfVaco/ExBDJK3zmNbb6IDlZkq67ip48foVOCiDtstCtv43WAlvIZ/i+rPOGHirAN6PJueVUmfSUyvKqQsTFsM01zzvj823nqz91Bf/+eYyci9s6Olt21c99sqLxO396VuB40LicfaH9KX53f2VUrE130j3xt2u6hzhYy0Wz05s7dU4njTaEqlZwqtx/WqbQTj1VliExwnV7hkJNcLPT4EhNDwp2B2ZTm0x3MuD7+1aYvxz6uSqJDsn8a7ZzEdKEfLiZ8uBq2LhFPU5/oX4gwgLvLd2e7CO86LSwWhK7Gk1eBE1iAwnpYujkZvcxKXMTULhCRk+4g2u334gBFGwq+908VCkbYKg=
      