global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#kroshin_kirill'
